-- MySQL Script generated by MySQL Workbench
-- Mon Apr 11 14:41:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cocina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cocina` (
  `idCocina` INT NOT NULL,
  `n_personas` VARCHAR(45) NULL,
  PRIMARY KEY (`idCocina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`terminalVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`terminalVenta` (
  `idterminalVenta` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Cliente_idCliente1` INT NOT NULL,
  PRIMARY KEY (`idterminalVenta`, `Cliente_idCliente`, `Cliente_idCliente1`),
  INDEX `fk_terminalVenta_Cliente1_idx` (`Cliente_idCliente1` ASC) VISIBLE,
  CONSTRAINT `fk_terminalVenta_Cliente1`
    FOREIGN KEY (`Cliente_idCliente1`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `timestamp` DATE NULL,
  `estado_pediido` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `terminalVenta_idterminalVenta` INT NOT NULL,
  `terminalVenta_Cliente_idCliente` INT NOT NULL,
  `terminalVenta_Cliente_idCliente1` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`, `terminalVenta_idterminalVenta`, `terminalVenta_Cliente_idCliente`, `terminalVenta_Cliente_idCliente1`),
  INDEX `fk_Pedido_terminalVenta1_idx` (`terminalVenta_idterminalVenta` ASC, `terminalVenta_Cliente_idCliente` ASC, `terminalVenta_Cliente_idCliente1` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_terminalVenta1`
    FOREIGN KEY (`terminalVenta_idterminalVenta` , `terminalVenta_Cliente_idCliente` , `terminalVenta_Cliente_idCliente1`)
    REFERENCES `mydb`.`terminalVenta` (`idterminalVenta` , `Cliente_idCliente` , `Cliente_idCliente1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Delivery` (
  `idDelivery` INT NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  `direccion` VARCHAR(255) NULL,
  PRIMARY KEY (`idDelivery`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`),
  INDEX `fk_Delivery_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Delivery_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estadoCivil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estadoCivil` (
  `idestadoCivil` INT NOT NULL,
  `estado_civil` VARCHAR(45) NULL,
  PRIMARY KEY (`idestadoCivil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `idRol` INT NOT NULL,
  `tipo_cargo` VARCHAR(105) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trabajador` (
  `rut` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `Cocina_idCocina` INT NOT NULL,
  `Delivery_idDelivery` INT NOT NULL,
  `Delivery_Pedido_idPedido` INT NOT NULL,
  `Delivery_Pedido_Cliente_idCliente` INT NOT NULL,
  `estadoCivil_idestadoCivil` INT NOT NULL,
  `Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`rut`, `Cocina_idCocina`, `Delivery_idDelivery`, `Delivery_Pedido_idPedido`, `Delivery_Pedido_Cliente_idCliente`, `estadoCivil_idestadoCivil`, `Rol_idRol`),
  INDEX `fk_trabajador_Cocina1_idx` (`Cocina_idCocina` ASC) VISIBLE,
  INDEX `fk_trabajador_Delivery1_idx` (`Delivery_idDelivery` ASC, `Delivery_Pedido_idPedido` ASC, `Delivery_Pedido_Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_trabajador_estadoCivil1_idx` (`estadoCivil_idestadoCivil` ASC) VISIBLE,
  INDEX `fk_trabajador_Rol1_idx` (`Rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_trabajador_Cocina1`
    FOREIGN KEY (`Cocina_idCocina`)
    REFERENCES `mydb`.`Cocina` (`idCocina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajador_Delivery1`
    FOREIGN KEY (`Delivery_idDelivery` , `Delivery_Pedido_idPedido` , `Delivery_Pedido_Cliente_idCliente`)
    REFERENCES `mydb`.`Delivery` (`idDelivery` , `Pedido_idPedido` , `Pedido_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajador_estadoCivil1`
    FOREIGN KEY (`estadoCivil_idestadoCivil`)
    REFERENCES `mydb`.`estadoCivil` (`idestadoCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajador_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `mydb`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comuna` (
  `idComuna` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `trabajador_rut` INT NOT NULL,
  `trabajador_Cocina_idCocina` INT NOT NULL,
  `trabajador_Delivery_idDelivery` INT NOT NULL,
  `trabajador_Delivery_Pedido_idPedido` INT NOT NULL,
  `trabajador_Delivery_Pedido_Cliente_idCliente` INT NOT NULL,
  `trabajador_estadoCivil_idestadoCivil` INT NOT NULL,
  PRIMARY KEY (`idComuna`, `Cliente_idCliente`, `trabajador_rut`, `trabajador_Cocina_idCocina`, `trabajador_Delivery_idDelivery`, `trabajador_Delivery_Pedido_idPedido`, `trabajador_Delivery_Pedido_Cliente_idCliente`, `trabajador_estadoCivil_idestadoCivil`),
  INDEX `fk_Comuna_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Comuna_trabajador1_idx` (`trabajador_rut` ASC, `trabajador_Cocina_idCocina` ASC, `trabajador_Delivery_idDelivery` ASC, `trabajador_Delivery_Pedido_idPedido` ASC, `trabajador_Delivery_Pedido_Cliente_idCliente` ASC, `trabajador_estadoCivil_idestadoCivil` ASC) VISIBLE,
  CONSTRAINT `fk_Comuna_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comuna_trabajador1`
    FOREIGN KEY (`trabajador_rut` , `trabajador_Cocina_idCocina` , `trabajador_Delivery_idDelivery` , `trabajador_Delivery_Pedido_idPedido` , `trabajador_Delivery_Pedido_Cliente_idCliente` , `trabajador_estadoCivil_idestadoCivil`)
    REFERENCES `mydb`.`trabajador` (`rut` , `Cocina_idCocina` , `Delivery_idDelivery` , `Delivery_Pedido_idPedido` , `Delivery_Pedido_Cliente_idCliente` , `estadoCivil_idestadoCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `idMenu` INT NOT NULL AUTO_INCREMENT,
  `cantidad_items` INT NOT NULL,
  `terminalVenta_idterminalVenta` INT NOT NULL,
  `terminalVenta_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idMenu`, `terminalVenta_idterminalVenta`, `terminalVenta_Cliente_idCliente`),
  INDEX `fk_Menu_terminalVenta1_idx` (`terminalVenta_idterminalVenta` ASC, `terminalVenta_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Menu_terminalVenta1`
    FOREIGN KEY (`terminalVenta_idterminalVenta` , `terminalVenta_Cliente_idCliente`)
    REFERENCES `mydb`.`terminalVenta` (`idterminalVenta` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipoProducto` (
  `idtipoProducto` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `stock_disponible` TINYINT NULL,
  PRIMARY KEY (`idtipoProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `tiempo_preparacion` INT NULL,
  `Menu_idMenu` INT NOT NULL,
  `Menu_terminalVenta_idterminalVenta` INT NOT NULL,
  `Menu_terminalVenta_Cliente_idCliente` INT NOT NULL,
  `tipoProducto_idtipoProducto` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `Menu_idMenu`, `Menu_terminalVenta_idterminalVenta`, `Menu_terminalVenta_Cliente_idCliente`, `tipoProducto_idtipoProducto`),
  INDEX `fk_Producto_Menu1_idx` (`Menu_idMenu` ASC, `Menu_terminalVenta_idterminalVenta` ASC, `Menu_terminalVenta_Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Producto_tipoProducto1_idx` (`tipoProducto_idtipoProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Menu1`
    FOREIGN KEY (`Menu_idMenu` , `Menu_terminalVenta_idterminalVenta` , `Menu_terminalVenta_Cliente_idCliente`)
    REFERENCES `mydb`.`Menu` (`idMenu` , `terminalVenta_idterminalVenta` , `terminalVenta_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_tipoProducto1`
    FOREIGN KEY (`tipoProducto_idtipoProducto`)
    REFERENCES `mydb`.`tipoProducto` (`idtipoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Precio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Precio` (
  `idPrecio` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `Producto_Menu_idMenu` INT NOT NULL,
  `Producto_Menu_terminalVenta_idterminalVenta` INT NOT NULL,
  `Producto_Menu_terminalVenta_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPrecio`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`, `Producto_idProducto`, `Producto_Menu_idMenu`, `Producto_Menu_terminalVenta_idterminalVenta`, `Producto_Menu_terminalVenta_Cliente_idCliente`),
  INDEX `fk_Precio_Producto1_idx` (`Producto_idProducto` ASC, `Producto_Menu_idMenu` ASC, `Producto_Menu_terminalVenta_idterminalVenta` ASC, `Producto_Menu_terminalVenta_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Precio_Producto1`
    FOREIGN KEY (`Producto_idProducto` , `Producto_Menu_idMenu` , `Producto_Menu_terminalVenta_idterminalVenta` , `Producto_Menu_terminalVenta_Cliente_idCliente`)
    REFERENCES `mydb`.`Producto` (`idProducto` , `Menu_idMenu` , `Menu_terminalVenta_idterminalVenta` , `Menu_terminalVenta_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pago` (
  `idPago` INT NOT NULL,
  `fecha` DATE NULL,
  `tipo_pago` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  `Pedido_terminalVenta_idterminalVenta` INT NOT NULL,
  `Pedido_terminalVenta_Cliente_idCliente` INT NOT NULL,
  `Pedido_terminalVenta_Cliente_idCliente1` INT NOT NULL,
  PRIMARY KEY (`idPago`, `Cliente_idCliente`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`, `Pedido_terminalVenta_idterminalVenta`, `Pedido_terminalVenta_Cliente_idCliente`, `Pedido_terminalVenta_Cliente_idCliente1`),
  INDEX `fk_Pago_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_idCliente` ASC, `Pedido_terminalVenta_idterminalVenta` ASC, `Pedido_terminalVenta_Cliente_idCliente` ASC, `Pedido_terminalVenta_Cliente_idCliente1` ASC) VISIBLE,
  CONSTRAINT `fk_Pago_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente` , `Pedido_terminalVenta_idterminalVenta` , `Pedido_terminalVenta_Cliente_idCliente` , `Pedido_terminalVenta_Cliente_idCliente1`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente` , `terminalVenta_idterminalVenta` , `terminalVenta_Cliente_idCliente` , `terminalVenta_Cliente_idCliente1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Boleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Boleta` (
  `idBoleta` INT NOT NULL,
  `codigo_pago` VARCHAR(45) NULL,
  `tipo_pago` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  PRIMARY KEY (`idBoleta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comanda` (
  `idComanda` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  `Cocina_idCocina` INT NOT NULL,
  PRIMARY KEY (`idComanda`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`, `Cocina_idCocina`),
  INDEX `fk_Comanda_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Comanda_Cocina1_idx` (`Cocina_idCocina` ASC) VISIBLE,
  CONSTRAINT `fk_Comanda_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comanda_Cocina1`
    FOREIGN KEY (`Cocina_idCocina`)
    REFERENCES `mydb`.`Cocina` (`idCocina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `terminalVenta_idterminalVenta` INT NOT NULL,
  `terminalVenta_Cliente_idCliente` INT NOT NULL,
  `terminalVenta_Cliente_idCliente1` INT NOT NULL,
  `Comanda_idComanda` INT NOT NULL,
  `Comanda_Pedido_idPedido` INT NOT NULL,
  `Comanda_Pedido_Cliente_idCliente` INT NOT NULL,
  `Comanda_Cocina_idCocina` INT NOT NULL,
  PRIMARY KEY (`terminalVenta_idterminalVenta`, `terminalVenta_Cliente_idCliente`, `terminalVenta_Cliente_idCliente1`, `Comanda_idComanda`, `Comanda_Pedido_idPedido`, `Comanda_Pedido_Cliente_idCliente`, `Comanda_Cocina_idCocina`),
  INDEX `fk_timestamps_Comanda1_idx` (`Comanda_idComanda` ASC, `Comanda_Pedido_idPedido` ASC, `Comanda_Pedido_Cliente_idCliente` ASC, `Comanda_Cocina_idCocina` ASC) VISIBLE,
  CONSTRAINT `fk_timestamps_terminalVenta1`
    FOREIGN KEY (`terminalVenta_idterminalVenta` , `terminalVenta_Cliente_idCliente` , `terminalVenta_Cliente_idCliente1`)
    REFERENCES `mydb`.`terminalVenta` (`idterminalVenta` , `Cliente_idCliente` , `Cliente_idCliente1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timestamps_Comanda1`
    FOREIGN KEY (`Comanda_idComanda` , `Comanda_Pedido_idPedido` , `Comanda_Pedido_Cliente_idCliente` , `Comanda_Cocina_idCocina`)
    REFERENCES `mydb`.`Comanda` (`idComanda` , `Pedido_idPedido` , `Pedido_Cliente_idCliente` , `Cocina_idCocina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `idVenta` INT NOT NULL,
  `procedencia_venta` VARCHAR(45) NULL,
  `Pago_idPago` INT NOT NULL,
  `Pago_Cliente_idCliente` INT NOT NULL,
  `Boleta_idBoleta` INT NOT NULL,
  `Pago_idPago1` INT NOT NULL,
  `Pago_Cliente_idCliente1` INT NOT NULL,
  `Pago_Pedido_idPedido` INT NOT NULL,
  `Pago_Pedido_Cliente_idCliente` INT NOT NULL,
  `Pago_Pedido_terminalVenta_idterminalVenta` INT NOT NULL,
  `Pago_Pedido_terminalVenta_Cliente_idCliente` INT NOT NULL,
  `Pago_Pedido_terminalVenta_Cliente_idCliente1` INT NOT NULL,
  `timestamps_terminalVenta_idterminalVenta` INT NOT NULL,
  `timestamps_terminalVenta_Cliente_idCliente` INT NOT NULL,
  `timestamps_terminalVenta_Cliente_idCliente1` INT NOT NULL,
  `timestamps_Comanda_idComanda` INT NOT NULL,
  `timestamps_Comanda_Pedido_idPedido` INT NOT NULL,
  `timestamps_Comanda_Pedido_Cliente_idCliente` INT NOT NULL,
  `timestamps_Comanda_Cocina_idCocina` INT NOT NULL,
  PRIMARY KEY (`idVenta`, `Pago_idPago`, `Pago_Cliente_idCliente`, `Boleta_idBoleta`, `Pago_idPago1`, `Pago_Cliente_idCliente1`, `Pago_Pedido_idPedido`, `Pago_Pedido_Cliente_idCliente`, `Pago_Pedido_terminalVenta_idterminalVenta`, `Pago_Pedido_terminalVenta_Cliente_idCliente`, `Pago_Pedido_terminalVenta_Cliente_idCliente1`, `timestamps_terminalVenta_idterminalVenta`, `timestamps_terminalVenta_Cliente_idCliente`, `timestamps_terminalVenta_Cliente_idCliente1`, `timestamps_Comanda_idComanda`, `timestamps_Comanda_Pedido_idPedido`, `timestamps_Comanda_Pedido_Cliente_idCliente`, `timestamps_Comanda_Cocina_idCocina`),
  INDEX `fk_Venta_Boleta1_idx` (`Boleta_idBoleta` ASC) VISIBLE,
  INDEX `fk_Venta_Pago1_idx` (`Pago_idPago1` ASC, `Pago_Cliente_idCliente1` ASC, `Pago_Pedido_idPedido` ASC, `Pago_Pedido_Cliente_idCliente` ASC, `Pago_Pedido_terminalVenta_idterminalVenta` ASC, `Pago_Pedido_terminalVenta_Cliente_idCliente` ASC, `Pago_Pedido_terminalVenta_Cliente_idCliente1` ASC) VISIBLE,
  INDEX `fk_Venta_timestamps1_idx` (`timestamps_terminalVenta_idterminalVenta` ASC, `timestamps_terminalVenta_Cliente_idCliente` ASC, `timestamps_terminalVenta_Cliente_idCliente1` ASC, `timestamps_Comanda_idComanda` ASC, `timestamps_Comanda_Pedido_idPedido` ASC, `timestamps_Comanda_Pedido_Cliente_idCliente` ASC, `timestamps_Comanda_Cocina_idCocina` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_Boleta1`
    FOREIGN KEY (`Boleta_idBoleta`)
    REFERENCES `mydb`.`Boleta` (`idBoleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Pago1`
    FOREIGN KEY (`Pago_idPago1` , `Pago_Cliente_idCliente1` , `Pago_Pedido_idPedido` , `Pago_Pedido_Cliente_idCliente` , `Pago_Pedido_terminalVenta_idterminalVenta` , `Pago_Pedido_terminalVenta_Cliente_idCliente` , `Pago_Pedido_terminalVenta_Cliente_idCliente1`)
    REFERENCES `mydb`.`Pago` (`idPago` , `Cliente_idCliente` , `Pedido_idPedido` , `Pedido_Cliente_idCliente` , `Pedido_terminalVenta_idterminalVenta` , `Pedido_terminalVenta_Cliente_idCliente` , `Pedido_terminalVenta_Cliente_idCliente1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_timestamps1`
    FOREIGN KEY (`timestamps_terminalVenta_idterminalVenta` , `timestamps_terminalVenta_Cliente_idCliente` , `timestamps_terminalVenta_Cliente_idCliente1` , `timestamps_Comanda_idComanda` , `timestamps_Comanda_Pedido_idPedido` , `timestamps_Comanda_Pedido_Cliente_idCliente` , `timestamps_Comanda_Cocina_idCocina`)
    REFERENCES `mydb`.`timestamps` (`terminalVenta_idterminalVenta` , `terminalVenta_Cliente_idCliente` , `terminalVenta_Cliente_idCliente1` , `Comanda_idComanda` , `Comanda_Pedido_idPedido` , `Comanda_Pedido_Cliente_idCliente` , `Comanda_Cocina_idCocina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalle` (
  `idDetalle` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `Venta_idVenta` INT NOT NULL,
  `Venta_Pago_idPago` INT NOT NULL,
  `Venta_Pago_Cliente_idCliente` INT NOT NULL,
  `Venta_Boleta_idBoleta` INT NOT NULL,
  PRIMARY KEY (`idDetalle`, `Venta_idVenta`, `Venta_Pago_idPago`, `Venta_Pago_Cliente_idCliente`, `Venta_Boleta_idBoleta`),
  INDEX `fk_Detalle_Venta1_idx` (`Venta_idVenta` ASC, `Venta_Pago_idPago` ASC, `Venta_Pago_Cliente_idCliente` ASC, `Venta_Boleta_idBoleta` ASC) VISIBLE,
  CONSTRAINT `fk_Detalle_Venta1`
    FOREIGN KEY (`Venta_idVenta` , `Venta_Pago_idPago` , `Venta_Pago_Cliente_idCliente` , `Venta_Boleta_idBoleta`)
    REFERENCES `mydb`.`Venta` (`idVenta` , `Pago_idPago` , `Pago_Cliente_idCliente` , `Boleta_idBoleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipolicencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipolicencia` (
  `idtipo` INT NOT NULL,
  `clase` VARCHAR(45) NULL,
  `chofer_idchofer` INT NOT NULL,
  `trabajador_rut` INT NOT NULL,
  `trabajador_Cocina_idCocina` INT NOT NULL,
  PRIMARY KEY (`idtipo`, `chofer_idchofer`, `trabajador_rut`, `trabajador_Cocina_idCocina`),
  INDEX `fk_tipolicencia_trabajador1_idx` (`trabajador_rut` ASC, `trabajador_Cocina_idCocina` ASC) VISIBLE,
  CONSTRAINT `fk_tipolicencia_trabajador1`
    FOREIGN KEY (`trabajador_rut` , `trabajador_Cocina_idCocina`)
    REFERENCES `mydb`.`trabajador` (`rut` , `Cocina_idCocina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoPago` (
  `idTipoPago` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL,
  `Pago_idPago` INT NOT NULL,
  `Pago_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idTipoPago`, `Pago_idPago`, `Pago_Cliente_idCliente`),
  INDEX `fk_TipoPago_Pago1_idx` (`Pago_idPago` ASC, `Pago_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_TipoPago_Pago1`
    FOREIGN KEY (`Pago_idPago` , `Pago_Cliente_idCliente`)
    REFERENCES `mydb`.`Pago` (`idPago` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
